// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSt7YQFdF1x5dAP8Im1AAlkbbpKB-AGs',
    appId: '1:495272976160:web:a9affac0e79a867f93c145',
    messagingSenderId: '495272976160',
    projectId: 'booking-app-2e20b',
    authDomain: 'booking-app-2e20b.firebaseapp.com',
    storageBucket: 'booking-app-2e20b.appspot.com',
    measurementId: 'G-JBXH5J25HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkxeJ_G6VO0-F6qifqZ-7RRHswrOiHCg',
    appId: '1:495272976160:android:b75307c0dd25c2e593c145',
    messagingSenderId: '495272976160',
    projectId: 'booking-app-2e20b',
    storageBucket: 'booking-app-2e20b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NSk-ykbhjR9MfMKTxpLe8F0O7QiyF_4',
    appId: '1:495272976160:ios:de7729e3b238eb3093c145',
    messagingSenderId: '495272976160',
    projectId: 'booking-app-2e20b',
    storageBucket: 'booking-app-2e20b.appspot.com',
    iosBundleId: 'com.example.testappBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NSk-ykbhjR9MfMKTxpLe8F0O7QiyF_4',
    appId: '1:495272976160:ios:de7729e3b238eb3093c145',
    messagingSenderId: '495272976160',
    projectId: 'booking-app-2e20b',
    storageBucket: 'booking-app-2e20b.appspot.com',
    iosBundleId: 'com.example.testappBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSt7YQFdF1x5dAP8Im1AAlkbbpKB-AGs',
    appId: '1:495272976160:web:657a9e9f4ed49aa893c145',
    messagingSenderId: '495272976160',
    projectId: 'booking-app-2e20b',
    authDomain: 'booking-app-2e20b.firebaseapp.com',
    storageBucket: 'booking-app-2e20b.appspot.com',
    measurementId: 'G-ZZH3MDXS4C',
  );
}
